In [1]:
#Pertama kita import library yang akan dipakai
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
#lalu kita masukkan dataset, kali ini saya meminjam dataset dari DQLab
url = "https://academy.dqlab.id/dataset/data_transaksi2.txt"
df = pd.read_csv(url, sep="\t")

In [3]:
#Lihat data yang sudah di baca
df

     Kode Transaksi                Nama Barang
0                #1                       Kaos
1                #1               Shampo Biasa
2                #1        Sepatu Sport merk Z
3                #1              Serum Vitamin
4                #1    Baju Renang Pria Dewasa
...             ...                        ...
9730          #1000              Serum Vitamin
9731          #1000    Baju Renang Pria Dewasa
9732          #1000       Celana Pendek Casual
9733          #1000  Tali Pinggang Gesper Pria
9734          #1000        Tali Pinggang Anaks

[9735 rows x 2 columns]

In [4]:
#Kita juga bisa melihat item-item unik, beserta jumlahnya, contoh dibawah item yang paling laku adalah shampo biasa yang telah terjual 604 kali, begitu juga barang yang paling jarang laku seperti Tali Pinggang anak yang hanya terjual sekali
df['Nama Barang'].value_counts()

Shampo Biasa                  604
Serum Vitamin                 510
Baju Batik Wanita             366
Baju Kemeja Putih             359
Celana Jogger Casual          336
                             ...
Baju Renang Pria Anak-anak      6
Celana Jeans Sobek Pria         5
Tas Kosmetik                    3
Stripe Pants                    3
Tali Pinggang Anaks             1
Name: Nama Barang, Length: 70, dtype: int64

In [5]:
#Kita mulai data preprocessing, pertama saya encoding itemset agar berubah menjadi integer, karna algortima hanya membaca angka
transaksi = pd.get_dummies(df, columns=['Nama Barang'])

In [6]:
#Lalu saya mengelompokkanya berdasarkan dengan kode transaksinya
transaksi = transaksi.groupby('Kode Transaksi').sum()

In [7]:
#kita lihat data yang sudah kita proses sebelumnya
transaksi

,Nama Barang_Atasan Baju Belang,Nama Barang_Atasan Kaos Putih,Nama Barang_Baju Batik Wanita,Nama Barang_Baju Kaos Anak - Karakter Kartun,Nama Barang_Baju Kaos Anak - Superheroes,Nama Barang_Baju Kaos Olahraga,Nama Barang_Baju Kemeja Putih,Nama Barang_Baju Renang Anak Perempuan,Nama Barang_Baju Renang Pria Anak-anak,Nama Barang_Baju Renang Pria Dewasa,...,Nama Barang_Tas Multifungsi,Nama Barang_Tas Pinggang Wanita,Nama Barang_Tas Ransel Mini,Nama Barang_Tas Sekolah Anak Laki-laki,Nama Barang_Tas Sekolah Anak Perempuan,Nama Barang_Tas Tangan,Nama Barang_Tas Travel,Nama Barang_Tas Waist Bag,Nama Barang_Wedges Hitam,Nama Barang_Woman Ripped Jeans
Kode Transaksi,,,,,,,,,,,,,,,,,,,,,
#1,0,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
#10,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
#100,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
#1000,0,0,1,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
#101,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
#995,0,1,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,1,0,1,0
#996,0,0,0,0,0,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0
#997,0,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
#998,0,0,1,0,1,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
#999,0,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [8]:
#Mari kita cek lebih mendetail, apakah ada baris yang kosong? Jika kita lihat keterangan di bawah, data sudah bagus dan siap untuk dipakai
transaksi.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, #1 to #999
Data columns (total 70 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Nama Barang_Atasan Baju Belang                1000 non-null   uint8
 1   Nama Barang_Atasan Kaos Putih                 1000 non-null   uint8
 2   Nama Barang_Baju Batik Wanita                 1000 non-null   uint8
 3   Nama Barang_Baju Kaos Anak - Karakter Kartun  1000 non-null   uint8
 4   Nama Barang_Baju Kaos Anak - Superheroes      1000 non-null   uint8
 5   Nama Barang_Baju Kaos Olahraga                1000 non-null   uint8
 6   Nama Barang_Baju Kemeja Putih                 1000 non-null   uint8
 7   Nama Barang_Baju Renang Anak Perempuan        1000 non-null   uint8
 8   Nama Barang_Baju Renang Pria Anak-anak        1000 non-null   uint8
 9   Nama Barang_Baju Renang Pria Dewasa           1000 non-null   uint8
 10  Nama Barang_Baju Renang Wanita Dewasa         1000 non-null   uint8
 11  Nama Barang_Blouse Denim                      1000 non-null   uint8
 12  Nama Barang_Celana Jeans Sobek Pria           1000 non-null   uint8
 13  Nama Barang_Celana Jeans Sobek Wanita         1000 non-null   uint8
 14  Nama Barang_Celana Jogger Casual              1000 non-null   uint8
 15  Nama Barang_Celana Panjang Format Hitam       1000 non-null   uint8
 16  Nama Barang_Celana Pendek Casual              1000 non-null   uint8
 17  Nama Barang_Celana Pendek Green/Hijau         1000 non-null   uint8
 18  Nama Barang_Celana Pendek Jeans               1000 non-null   uint8
 19  Nama Barang_Celana Tactical                   1000 non-null   uint8
 20  Nama Barang_Cover Koper                       1000 non-null   uint8
 21  Nama Barang_Cream Whitening                   1000 non-null   uint8
 22  Nama Barang_Dompet Card Holder                1000 non-null   uint8
 23  Nama Barang_Dompet Flip Cover                 1000 non-null   uint8
 24  Nama Barang_Dompet Kulit Pria                 1000 non-null   uint8
 25  Nama Barang_Dompet STNK Gantungan             1000 non-null   uint8
 26  Nama Barang_Dompet Unisex                     1000 non-null   uint8
 27  Nama Barang_Flat Shoes Ballerina              1000 non-null   uint8
 28  Nama Barang_Gembok Koper                      1000 non-null   uint8
 29  Nama Barang_Hair Dryer                        1000 non-null   uint8
 30  Nama Barang_Hair Dye                          1000 non-null   uint8
 31  Nama Barang_Hair Tonic                        1000 non-null   uint8
 32  Nama Barang_Hair and Scalp                    1000 non-null   uint8
 33  Nama Barang_Jeans Jumbo                       1000 non-null   uint8
 34  Nama Barang_Kaos                              1000 non-null   uint8
 35  Nama Barang_Koper Fiber                       1000 non-null   uint8
 36  Nama Barang_Kuas Makeup                       1000 non-null   uint8
 37  Nama Barang_Mascara                           1000 non-null   uint8
 38  Nama Barang_Minyak Rambut                     1000 non-null   uint8
 39  Nama Barang_Obat Penumbuh Rambut              1000 non-null   uint8
 40  Nama Barang_Pelembab                          1000 non-null   uint8
 41  Nama Barang_Sepatu Kulit Casual               1000 non-null   uint8
 42  Nama Barang_Sepatu Sandal Anak                1000 non-null   uint8
 43  Nama Barang_Sepatu Sekolah Hitam W            1000 non-null   uint8
 44  Nama Barang_Sepatu Sport merk Y               1000 non-null   uint8
 45  Nama Barang_Sepatu Sport merk Z               1000 non-null   uint8
 46  Nama Barang_Serum Vitamin                     1000 non-null   uint8
 47  Nama Barang_Shampo Anti Dandruff              1000 non-null   uint8
 48  Nama Barang_Shampo Biasa                      1000 non-null   uint8
 49  Nama Barang_Stripe Pants                      1000 non-null   uint8
 50  Nama Barang_Sunblock Cream                    1000 non-null   uint8
 51  Nama Barang_Sweater Top Panjang               1000 non-null   uint8
 52  Nama Barang_Tali Ban Ikat Pinggang            1000 non-null   uint8
 53  Nama Barang_Tali Pinggang Anak                1000 non-null   uint8
 54  Nama Barang_Tali Pinggang Anaks               1000 non-null   uint8
 55  Nama Barang_Tali Pinggang Gesper Pria         1000 non-null   uint8
 56  Nama Barang_Tank Top                          1000 non-null   uint8
 57  Nama Barang_Tas Kosmetik                      1000 non-null   uint8
 58  Nama Barang_Tas Kulit Selempang               1000 non-null   uint8
 59  Nama Barang_Tas Makeup                        1000 non-null   uint8
 60  Nama Barang_Tas Multifungsi                   1000 non-null   uint8
 61  Nama Barang_Tas Pinggang Wanita               1000 non-null   uint8
 62  Nama Barang_Tas Ransel Mini                   1000 non-null   uint8
 63  Nama Barang_Tas Sekolah Anak Laki-laki        1000 non-null   uint8
 64  Nama Barang_Tas Sekolah Anak Perempuan        1000 non-null   uint8
 65  Nama Barang_Tas Tangan                        1000 non-null   uint8
 66  Nama Barang_Tas Travel                        1000 non-null   uint8
 67  Nama Barang_Tas Waist Bag                     1000 non-null   uint8
 68  Nama Barang_Wedges Hitam                      1000 non-null   uint8
 69  Nama Barang_Woman Ripped Jeans                1000 non-null   uint8
dtypes: uint8(70)
memory usage: 76.2+ KB

In [9]:
#Selanjutnya adalah membuat variabel dimana terdiri dari beberapa barang yang sering / terbeli dari seluruh transaksi menggunakan perintah apriori
itemset = apriori(transaksi, min_support=0.1, use_colnames=True)

In [10]:
itemset

     support                                           itemsets
0      0.128                    (Nama Barang_Atasan Kaos Putih)
1      0.366                    (Nama Barang_Baju Batik Wanita)
2      0.108     (Nama Barang_Baju Kaos Anak - Karakter Kartun)
3      0.116         (Nama Barang_Baju Kaos Anak - Superheroes)
4      0.359                    (Nama Barang_Baju Kemeja Putih)
..       ...                                                ...
99     0.136  (Nama Barang_Serum Vitamin, Nama Barang_Baju K...
100    0.107  (Nama Barang_Tali Pinggang Gesper Pria, Nama B...
101    0.107  (Nama Barang_Serum Vitamin, Nama Barang_Celana...
102    0.170  (Nama Barang_Serum Vitamin, Nama Barang_Sepatu...
103    0.103  (Nama Barang_Serum Vitamin, Nama Barang_Tali P...

[104 rows x 2 columns]

In [13]:
#Lalu mulai melihat kecocokan assosiasi data, kali ini saya menggunakan parameter yang sama seperti yang saya gunakan di R, yaitu support confidence adalah 80%, karna di Python jika minimal kita set 80, maka angka 80 tidak akan dihitung, jadi saya ubah menjadi 79, agar support 80 terhitung
rules = association_rules(itemset, metric="confidence", min_threshold=0.79)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Nama Barang_Celana Jeans Sobek Wanita),(Nama Barang_Shampo Biasa),0.240,0.604,0.209,0.870833,1.441777,0.064040,3.065806
1,(Nama Barang_Tas Waist Bag),(Nama Barang_Serum Vitamin),0.161,0.510,0.136,0.844720,1.656315,0.053890,3.155600
2,"(Nama Barang_Baju Batik Wanita, Nama Barang_Se...",(Nama Barang_Serum Vitamin),0.140,0.510,0.112,0.800000,1.568627,0.040600,2.450000
3,"(Nama Barang_Tali Pinggang Gesper Pria, Nama B...",(Nama Barang_Shampo Biasa),0.123,0.604,0.107,0.869919,1.440263,0.032708,3.044250

### Selesai, hasil sama persis dengan yang saya jalankan di R, kita sudah memiliki beberapa kombinasi terbaik,contoh seperti data di atas, jika orang membeli barang “celana jeans sobek wanita”, kita bisa menawarkan “shampo biasa”, atau kedua barang tersebut bisa kita paketkan langsung.. data di atas sudah cukup bagus dengan support 20% dari total 1000 transaksi, dan lift juga di atas 1